"""Synthetic Jira data source for screenshots, demos, and docs."""

from __future__ import annotations

from typing import Optional

from jira_cli.models import JiraIssue, JiraIssueField, JiraSearchResult
from jira_cli.quick_filters import normalize_for_match

DEMO_PROJECT_KEY = "DEMO"

_DEMO_ISSUES = [
    {
        "key": "DEMO-1",
        "summary": "Roll out dependency update workflow",
        "issuetype": "Story",
        "status": "Backlog",
        "priority": "High",
        "assignee": "Ada Lovelace",
        "updated": "2026-09-10T09:30:00.000+0000",
        "labels": ["automation", "security"],
    },
    {
        "key": "DEMO-2",
        "summary": "Review API token handling in CLI docs",
        "issuetype": "Task",
        "status": "To Do",
        "priority": "Medium",
        "assignee": "Grace Hopper",
        "updated": "2026-09-10T11:15:00.000+0000",
        "labels": ["docs"],
    },
    {
        "key": "DEMO-3",
        "summary": "Fix flaky TUI selection after refresh",
        "issuetype": "Bug",
        "status": "In Progress",
        "priority": "Highest",
        "assignee": "Marcel Körtgen",
        "updated": "2026-09-11T08:05:00.000+0000",
        "labels": ["tui", "quality"],
    },
    {
        "key": "DEMO-4",
        "summary": "Prepare release notes for v0.5.0",
        "issuetype": "Task",
        "status": "In Review",
        "priority": "Low",
        "assignee": "Katherine Johnson",
        "updated": "2026-09-11T13:40:00.000+0000",
        "labels": ["release"],
    },
    {
        "key": "DEMO-5",
        "summary": "Publish MkDocs API reference",
        "issuetype": "Story",
        "status": "Done",
        "priority": "Medium",
        "assignee": "Grace Hopper",
        "updated": "2026-09-11T16:20:00.000+0000",
        "labels": ["docs", "automation"],
    },
]

_DEMO_USERS = [
    {"accountId": "demo-ada", "displayName": "Ada Lovelace", "emailAddress": "ada@example.invalid", "active": True},
    {"accountId": "demo-grace", "displayName": "Grace Hopper", "emailAddress": "grace@example.invalid", "active": True},
    {"accountId": "demo-marcel", "displayName": "Marcel Körtgen", "emailAddress": "marcel@example.invalid", "active": True},
    {"accountId": "demo-katherine", "displayName": "Katherine Johnson", "emailAddress": "katherine@example.invalid", "active": True},
]

_DEMO_VERSIONS = [
    {"id": "demo-v050", "name": "v0.5.0", "description": "TUI resource views", "releaseDate": "2026-09-12", "released": False, "archived": False},
    {"id": "demo-v040", "name": "v0.4.0", "description": "CLI command groups", "releaseDate": "2026-08-30", "released": True, "archived": False},
]

_DEMO_COMMENTS = {
    "DEMO-3": [
        {
            "author": {"displayName": "Grace Hopper"},
            "created": "2026-09-11T08:20:00.000+0000",
            "body": "Reproduced in demo mode; prefetch should keep navigation responsive.",
        }
    ]
}


class DemoJiraClient:
    """JiraClient-compatible synthetic data source for safe screenshots."""

    base_url = "https://demo.atlassian.invalid"
    dry_run = True

    def search(
        self,
        jql: str,
        fields: Optional[list[str]] = None,
        start_at: int = 0,
        max_results: int = 50,
        expand: Optional[list[str]] = None,
    ) -> JiraSearchResult:
        """Search demo issues using the small JQL subset generated by JiraQuery."""
        rows = _filter_issues(jql)
        page = rows[start_at : start_at + max_results]
        return JiraSearchResult(issues=[_to_jira_issue(issue) for issue in page], total=len(rows), startAt=start_at, maxResults=max_results)

    def get_current_user(self) -> dict:
        """Return the synthetic authenticated user."""
        return _DEMO_USERS[2]

    def list_assignable_users(self, project_key: str, max_results: int = 50) -> list[dict]:
        """Return synthetic assignable users."""
        return _DEMO_USERS[:max_results]

    def find_assignable_users(self, project_key: str, query: str, max_results: int = 20) -> list[dict]:
        """Search synthetic assignable users."""
        normalized_query = normalize_for_match(query)
        users = [user for user in _DEMO_USERS if normalized_query in normalize_for_match(user.get("displayName", ""))]
        return users[:max_results]

    def search_users(self, query: str, max_results: int = 20) -> list[dict]:
        """Search synthetic users globally."""
        return self.find_assignable_users(DEMO_PROJECT_KEY, query, max_results=max_results)

    def list_versions(self, project_key: str) -> list[dict]:
        """Return synthetic fix versions/milestones."""
        return list(_DEMO_VERSIONS)

    def list_labels(self, project_key: str) -> list[dict]:
        """Return synthetic labels with issue counts."""
        counts: dict[str, int] = {}
        for issue in _DEMO_ISSUES:
            for label in issue["labels"]:
                counts[label] = counts.get(label, 0) + 1
        return [{"name": name, "issueCount": count} for name, count in sorted(counts.items())]

    def get_issue_comments(self, key: str, expand_changelog: bool = False) -> list[dict]:
        """Return synthetic comments for one issue."""
        return list(_DEMO_COMMENTS.get(key, []))

    def add_comment(self, key: str, body: str | dict, use_adf: bool = False) -> dict:
        """Pretend to add a comment in demo mode."""
        return {"id": "demo-comment", "body": body}

    def update_issue(self, key: str, fields: dict) -> None:
        """Pretend to update an issue in demo mode."""
        return None

    def get_transitions(self, key: str) -> list[dict]:
        """Return synthetic workflow transitions."""
        return [{"id": "demo-done", "name": "Done"}, {"id": "demo-progress", "name": "In Progress"}]

    def transition_issue(self, key: str, transition_id: str) -> None:
        """Pretend to transition an issue in demo mode."""
        return None

    def assign_issue(self, key: str, account_id: str) -> None:
        """Pretend to assign an issue in demo mode."""
        return None


def _to_jira_issue(issue: dict) -> JiraIssue:
    assignee = next((user for user in _DEMO_USERS if user["displayName"] == issue["assignee"]), None)
    return JiraIssue(
        key=issue["key"],
        fields=JiraIssueField(
            summary=issue["summary"],
            issuetype={"name": issue["issuetype"]},
            status={"name": issue["status"]},
            priority={"name": issue["priority"]},
            assignee=assignee,
            updated=issue["updated"],
            labels=issue["labels"],
        ),
    )


def _filter_issues(jql: str) -> list[dict]:
    query_part, _, order_part = jql.partition(" ORDER BY ")
    conditions = [condition.strip() for condition in query_part.split(" AND ")]
    rows = [issue for issue in _DEMO_ISSUES if _matches(issue, conditions)]
    return _sort_issues(rows, order_part)


def _matches(issue: dict, conditions: list[str]) -> bool:
    for condition in conditions:
        if not condition or condition.startswith("project ="):
            continue
        if condition == "assignee = currentUser()":
            if issue["assignee"] != "Marcel Körtgen":
                return False
            continue
        field, _, raw_value = condition.partition("=")
        field = field.strip()
        value = raw_value.strip().strip('"')
        if field == "key" and issue["key"] != value:
            return False
        if field == "issuetype" and issue["issuetype"] != value:
            return False
        if field == "status" and issue["status"] != value:
            return False
        if field == "assignee" and issue["assignee"] != value:
            return False
        if field == "priority" and issue["priority"] != value:
            return False
        if field == "labels" and value not in issue["labels"]:
            return False
    return True


def _sort_issues(rows: list[dict], order_part: str) -> list[dict]:
    if not order_part:
        return rows
    parts = order_part.split()
    field = parts[0]
    reverse = len(parts) > 1 and parts[1].upper() == "DESC"
    accessors = {
        "key": lambda issue: issue["key"],
        "priority": lambda issue: issue["priority"],
        "status": lambda issue: issue["status"],
        "issuetype": lambda issue: issue["issuetype"],
        "updated": lambda issue: issue["updated"],
    }
    accessor = accessors.get(field)
    return sorted(rows, key=accessor, reverse=reverse) if accessor else rows
